__all__ = [
    'test_cases',
]

test_cases = [
    ['',
     [
         ''
     ]
     ], [
        'a',
        [
            'a',
        ]
    ], [
        'b',
        [
            'b',
        ]
    ], [
        '1',
        [
            '1',
        ]
    ], [
        '\\|',
        [
            '|',
        ]
    ], [
        '\\+',
        [
            '+',
        ]
    ], [
        '\\?',
        [
            '?',
        ]
    ], [
        '\\\\',
        [
            '\\',
        ]
    ], [
        '\\(',
        [
            '(',
        ]
    ], [
        '\\)',
        [
            ')',
        ]
    ], [
        '\\[',
        [
            '[',
        ]
    ], [
        '\\]',
        [
            ']',
        ]
    ], [
        '()|()',
        [
            '',
        ]
    ], [
        'a|b',
        [
            'a',
            'b',
        ]
    ], [
        'a|1',
        [
            'a',
            '1',
        ]
    ], [
        'a|\\+',
        [
            'a',
            '+',
        ]
    ], [
        'a|b|c',
        [
            'a',
            'b',
            'c',
        ]
    ], [
        'a|b|c|d|e',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
        ]
    ], [
        '()()',
        [
            '',
        ]
    ], [
        'ab',
        [
            'ab',
        ]
    ], [
        'a1',
        [
            'a1',
        ]
    ], [
        'a\\+',
        [
            'a+',
        ]
    ], [
        'abc',
        [
            'abc',
        ]
    ], [
        'abcde',
        [
            'abcde',
        ]
    ], [
        'ab|cd',
        [
            'ab',
            'cd',
        ]
    ], [
        '(ab|cd)',
        [
            'ab',
            'cd',
        ]
    ], [
        '(ab)|(cd)',
        [
            'ab',
            'cd',
        ]
    ], [
        'a(b|c)d',
        [
            'abd',
            'acd',
        ]
    ], [
        '(ab|c)d',
        [
            'cd',
            'abd',
        ]
    ], [
        'a(b|cd)',
        [
            'ab',
            'acd',
        ]
    ], [
        '()*',
        [
            '',
        ]
    ], [
        'a*',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '1*',
        [
            '',
            '1',
            '11',
            '111',
            '1111',
            '11111',
        ]
    ], [
        '\\+*',
        [
            '',
            '+',
            '++',
            '+++',
            '++++',
            '+++++',
        ]
    ], [
        'ab*',
        [
            'a',
            'ab',
            'abb',
            'abbb',
            'abbbb',
            'abbbbb',
        ]
    ], [
        '(ab)*',
        [
            '',
            'ab',
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        'a|b*',
        [
            '',
            'a',
            'b',
            'bb',
            'bbb',
            'bbbb',
            'bbbbb',
        ]
    ], [
        '(a|b)*',
        [
            '',
            'a',
            'b',
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
            'aaaa',
            'aaab',
            'abab',
            'abbb',
            'baba',
            'bbbb',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'abbbb',
            'babab',
            'bbbbb',
            'aabbb',
            'aaabb',
            'ababab',
            'abbbbb',
            'bababa',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'bababab',
            'aaabbbb',
            'abababab',
            'babababa',
            'ababababa',
            'babababab',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '()+',
        [
            '',
        ]
    ], [
        'a+',
        [
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '1+',
        [
            '1',
            '11',
            '111',
            '1111',
            '11111',
        ]
    ], [
        '\\++',
        [
            '+',
            '++',
            '+++',
            '++++',
            '+++++',
        ]
    ], [
        'ab+',
        [
            'ab',
            'abb',
            'abbb',
            'abbbb',
            'abbbbb',
        ]
    ], [
        '(ab)+',
        [
            'ab',
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        'a|b+',
        [
            'a',
            'b',
            'bb',
            'bbb',
            'bbbb',
            'bbbbb',
        ]
    ], [
        '(a|b)+',
        [
            'a',
            'b',
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
            'aaaa',
            'aaab',
            'abab',
            'abbb',
            'baba',
            'bbbb',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'abbbb',
            'babab',
            'bbbbb',
            'aabbb',
            'aaabb',
            'ababab',
            'abbbbb',
            'bababa',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'bababab',
            'aaabbbb',
            'abababab',
            'babababa',
            'ababababa',
            'babababab',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '(()+)*',
        [
            '',
        ]
    ], [
        '(a+)*',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a*)+',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        'a*a+',
        [
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        'a+a*',
        [
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        'a*|b+',
        [
            '',
            'a',
            'b',
            'aa',
            'bb',
            'aaa',
            'bbb',
            'aaaa',
            'bbbb',
            'aaaaa',
            'bbbbb',
            'aaaaaa',
        ]
    ], [
        '()?',
        [
            '',
        ]
    ], [
        'a?',
        [
            '',
            'a',
        ]
    ], [
        '1?',
        [
            '',
            '1',
        ]
    ], [
        '\\+?',
        [
            '',
            '+',
        ]
    ], [
        'a?b',
        [
            'b',
            'ab',
        ]
    ], [
        'ab?',
        [
            'a',
            'ab',
        ]
    ], [
        '(ab)?',
        [
            '',
            'ab',
        ]
    ], [
        'a|b?',
        [
            '',
            'a',
            'b',
        ]
    ], [
        '(a|b)?',
        [
            '',
            'a',
            'b',
        ]
    ], [
        '(a*)?',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a?)*',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a+)?',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a?)+',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(){0}',
        [
            '',
        ]
    ], [
        '(){1}',
        [
            '',
        ]
    ], [
        'a{0}',
        [
            '',
        ]
    ], [
        'a{1}',
        [
            'a',
        ]
    ], [
        'a{3}',
        [
            'aaa',
        ]
    ], [
        'a{5}',
        [
            'aaaaa',
        ]
    ], [
        '\\+{0}',
        [
            '',
        ]
    ], [
        '\\+{1}',
        [
            '+',
        ]
    ], [
        '\\+{3}',
        [
            '+++',
        ]
    ], [
        'a{3}b',
        [
            'aaab',
        ]
    ], [
        'ab{3}',
        [
            'abbb',
        ]
    ], [
        '(ab){3}',
        [
            'ababab',
        ]
    ], [
        '(ab){5}',
        [
            'ababababab',
        ]
    ], [
        'a{3}|b',
        [
            'b',
            'aaa',
        ]
    ], [
        'a|b{3}',
        [
            'a',
            'bbb',
        ]
    ], [
        '(a|b){3}',
        [
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
        ]
    ], [
        '(a*){3}',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a{3})*',
        [
            '',
            'aaa',
            'aaaaaa',
        ]
    ], [
        '(a+){3}',
        [
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a{3})+',
        [
            'aaa',
            'aaaaaa',
        ]
    ], [
        '(a?){3}',
        [
            '',
            'a',
            'aa',
            'aaa',
        ]
    ], [
        '((ab)*){3}',
        [
            '',
            'ab',
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        '((ab)+){3}',
        [
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        '((ab)?){3}',
        [
            '',
            'ab',
            'abab',
            'ababab',
        ]
    ], [
        '(){0,3}',
        [
            '',
        ]
    ], [
        '(){2,4}',
        [
            '',
        ]
    ], [
        'a{0,3}',
        [
            '',
            'a',
            'aa',
            'aaa',
        ]
    ], [
        'a{2,4}',
        [
            'aa',
            'aaa',
            'aaaa',
        ]
    ], [
        '\\+{0,3}',
        [
            '',
            '+',
            '++',
            '+++',
        ]
    ], [
        '\\+{2,4}',
        [
            '++',
            '+++',
            '++++',
        ]
    ], [
        'a{0,3}b{2,4}',
        [
            'bb',
            'abb',
            'bbb',
            'abbb',
            'bbbb',
            'aabb',
            'abbbb',
            'aabbb',
            'aaabb',
            'aabbbb',
            'aaabbb',
            'aaabbbb',
        ]
    ], [
        '(ab){0,3}',
        [
            '',
            'ab',
            'abab',
            'ababab',
        ]
    ], [
        '(ab){2,4}',
        [
            'abab',
            'ababab',
            'abababab',
        ]
    ], [
        'a{0,3}|b{2,4}',
        [
            '',
            'a',
            'aa',
            'bb',
            'aaa',
            'bbb',
            'bbbb',
        ]
    ], [
        '(a|b){0,3}',
        [
            '',
            'a',
            'b',
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
        ]
    ], [
        '(a|b){2,4}',
        [
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
            'aaaa',
            'aaab',
            'abab',
            'abbb',
            'baba',
            'bbbb',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
        ]
    ], [
        '(a*){0,3}',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a*){2,4}',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a+){0,3}',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a+){2,4}',
        [
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        '(a?){0,3}',
        [
            '',
            'a',
            'aa',
            'aaa',
        ]
    ], [
        '(a?){2,4}',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
        ]
    ], [
        '((ab)*){0,3}',
        [
            '',
            'ab',
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        '((ab)*){2,4}',
        [
            '',
            'ab',
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        '((ab)+){0,3}',
        [
            '',
            'ab',
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        '((ab)+){2,4}',
        [
            'abab',
            'ababab',
            'abababab',
            'ababababab',
            'abababababab',
        ]
    ], [
        '((ab)?){0,3}',
        [
            '',
            'ab',
            'abab',
            'ababab',
        ]
    ], [
        '((ab)?){2,4}',
        [
            '',
            'ab',
            'abab',
            'ababab',
            'abababab',
        ]
    ], [
        '(a{2}){2,4}',
        [
            'aaaa',
            'aaaaaa',
        ]
    ], [
        '(a{0,3}){2}',
        [
            '',
            'a',
            'aa',
            'aaa',
            'aaaa',
            'aaaaa',
            'aaaaaa',
        ]
    ], [
        'a\\{1\\}',
        [
            'a{1}',
        ]
    ], [
        '[a]',
        [
            'a',
        ]
    ], [
        '[1]',
        [
            '1',
        ]
    ], [
        '[\\+]',
        [
            '+',
        ]
    ], [
        '[\\*]',
        [
            '*',
        ]
    ], [
        '[\\[]',
        [
            '[',
        ]
    ], [
        '[abc]',
        [
            'a',
            'b',
            'c',
        ]
    ], [
        '[ace]',
        [
            'a',
            'c',
            'e',
        ]
    ], [
        '[a1]',
        [
            'a',
            '1',
        ]
    ], [
        '[1a]',
        [
            'a',
            '1',
        ]
    ], [
        '[a\\+]',
        [
            'a',
            '+',
        ]
    ], [
        '[a1\\+]',
        [
            'a',
            '+',
            '1',
        ]
    ], [
        '[a-e]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
        ]
    ], [
        '[a-z]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
        ]
    ], [
        '[A-Z]',
        [
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '[a-zA-Z]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '[3-7]',
        [
            '3',
            '4',
            '5',
            '6',
            '7',
        ]
    ], [
        '[0-9]',
        [
            '1',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
        ]
    ], [
        '[a-zA-Z0-9]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '1',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '[a-zA-Z0-9\\+]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '+',
            '1',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '[a-zA-Z0-9_]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '1',
            '_',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '[]',
        []
    ], [
        '[a-cx-z]',
        [
            'a',
            'b',
            'c',
            'x',
            'y',
            'z',
        ]
    ], [
        '[ax-z]',
        [
            'a',
            'x',
            'y',
            'z',
        ]
    ], [
        '[a-cx]',
        [
            'a',
            'b',
            'c',
            'x',
        ]
    ], [
        '[-]',
        [
            '-',
        ]
    ], [
        '[a-]',
        [
            'a',
            '-',
        ]
    ], [
        '[-a]',
        [
            'a',
            '-',
        ]
    ], [
        '[ab-]',
        [
            'a',
            'b',
            '-',
        ]
    ], [
        '[-ab]',
        [
            'a',
            'b',
            '-',
        ]
    ], [
        '[-ab-]',
        [
            'a',
            'b',
            '-',
        ]
    ], [
        '[-a-c]',
        [
            'a',
            'b',
            'c',
            '-',
        ]
    ], [
        '[a-c-]',
        [
            'a',
            'b',
            'c',
            '-',
        ]
    ], [
        '[-a-c-]',
        [
            'a',
            'b',
            'c',
            '-',
        ]
    ], [
        '[-ax-z]',
        [
            'a',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[ax-z-]',
        [
            'a',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[-ax-z-]',
        [
            'a',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[-a-cx]',
        [
            'a',
            'b',
            'c',
            'x',
            '-',
        ]
    ], [
        '[a-cx-]',
        [
            'a',
            'b',
            'c',
            'x',
            '-',
        ]
    ], [
        '[-a-cx-]',
        [
            'a',
            'b',
            'c',
            'x',
            '-',
        ]
    ], [
        '[-a-cx-z]',
        [
            'a',
            'b',
            'c',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[a-cx-z-]',
        [
            'a',
            'b',
            'c',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[-a-cx-z-]',
        [
            'a',
            'b',
            'c',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[{]',
        [
            '{',
        ]
    ], [
        '[a-z-]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '-',
        ]
    ], [
        '[a-z{]',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '{',
        ]
    ], [
        '[]',
        []
    ],
    ['\\d',
     [
         '1',
         '0',
         '2',
         '3',
         '4',
         '5',
         '6',
         '7',
         '8',
         '9'
     ]
     ], [
        '\\w',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '1',
            '_',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '[ab]a',
        [
            'aa',
            'ba',
        ]
    ], [
        '[ab]1',
        [
            'a1',
            'b1',
        ]
    ], [
        'a[ab]',
        [
            'aa',
            'ab',
        ]
    ], [
        '1[ab]',
        [
            '1a',
        ]
    ], [
        '[ab][cd]',
        [
            'ac',
            'ad',
            'bc',
            'bd',
        ]
    ], [
        '[ab]|[cd]',
        [
            'a',
            'b',
            'c',
            'd',
        ]
    ], [
        '[ab]*',
        [
            '',
            'a',
            'b',
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
            'aaaa',
            'aaab',
            'abab',
            'abbb',
            'baba',
            'bbbb',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'abbbb',
            'babab',
            'bbbbb',
            'aabbb',
            'aaabb',
            'ababab',
            'abbbbb',
            'bababa',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'bababab',
            'aaabbbb',
            'abababab',
            'babababa',
            'ababababa',
            'babababab',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '[ab]+',
        [
            'a',
            'b',
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
            'aaaa',
            'aaab',
            'abab',
            'abbb',
            'baba',
            'bbbb',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'abbbb',
            'babab',
            'bbbbb',
            'aabbb',
            'aaabb',
            'ababab',
            'abbbbb',
            'bababa',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'bababab',
            'aaabbbb',
            'abababab',
            'babababa',
            'ababababa',
            'babababab',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '[ab]?',
        [
            '',
            'a',
            'b',
        ]
    ], [
        '[ab]{0}',
        [
            '',
        ]
    ], [
        '[ab]{3}',
        [
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
        ]
    ], [
        '[ab]{0,3}',
        [
            '',
            'a',
            'b',
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
        ]
    ], [
        '[ab]{2,4}',
        [
            'aa',
            'ab',
            'ba',
            'bb',
            'aaa',
            'aab',
            'aba',
            'abb',
            'baa',
            'bab',
            'bba',
            'bbb',
            'aaaa',
            'aaab',
            'abab',
            'abbb',
            'baba',
            'bbbb',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
        ]
    ], [
        '[a-e]*',
        [
            '',
            'a',
            'b',
            'c',
            'd',
            'e',
            'aa',
            'ab',
            'ac',
            'ad',
            'ae',
            'ba',
            'bb',
            'bc',
            'bd',
            'be',
            'cc',
            'cd',
            'ce',
            'aaa',
            'aab',
            'aac',
            'aad',
            'aba',
            'abb',
            'abc',
            'abd',
            'acc',
            'acd',
            'baa',
            'bab',
            'bac',
            'bba',
            'bbb',
            'bbc',
            'bbd',
            'bca',
            'bcc',
            'bcd',
            'cba',
            'ccc',
            'ccd',
            'aaaa',
            'aaab',
            'aabd',
            'abab',
            'abac',
            'abbb',
            'abbc',
            'abcc',
            'abcd',
            'accc',
            'baba',
            'bbbb',
            'bbcd',
            'bccc',
            'ccad',
            'cccc',
            'dcba',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'ababc',
            'abbbb',
            'abccc',
            'acccc',
            'babab',
            'bbaac',
            'bbbbb',
            'bcccc',
            'ccccc',
            'abcde',
            'aabbb',
            'aaabb',
            'aaabac',
            'ababab',
            'abbbbb',
            'abcccc',
            'accccc',
            'bababa',
            'bbbbbc',
            'cccccc',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'abccccc',
            'bababab',
            'bcccccc',
            'aaabbbb',
            'abababab',
            'ababbbbc',
            'abcccccc',
            'babababa',
            'ababaaabc',
            'ababababa',
            'babababab',
            'aaaaaaaaac',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '[a-e]+',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'aa',
            'ab',
            'ac',
            'ad',
            'ae',
            'ba',
            'bb',
            'bc',
            'bd',
            'be',
            'cc',
            'cd',
            'ce',
            'aaa',
            'aab',
            'aac',
            'aad',
            'aba',
            'abb',
            'abc',
            'abd',
            'acc',
            'acd',
            'baa',
            'bab',
            'bac',
            'bba',
            'bbb',
            'bbc',
            'bbd',
            'bca',
            'bcc',
            'bcd',
            'cba',
            'ccc',
            'ccd',
            'aaaa',
            'aaab',
            'aabd',
            'abab',
            'abac',
            'abbb',
            'abbc',
            'abcc',
            'abcd',
            'accc',
            'baba',
            'bbbb',
            'bbcd',
            'bccc',
            'ccad',
            'cccc',
            'dcba',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'ababc',
            'abbbb',
            'abccc',
            'acccc',
            'babab',
            'bbaac',
            'bbbbb',
            'bcccc',
            'ccccc',
            'abcde',
            'aabbb',
            'aaabb',
            'aaabac',
            'ababab',
            'abbbbb',
            'abcccc',
            'accccc',
            'bababa',
            'bbbbbc',
            'cccccc',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'abccccc',
            'bababab',
            'bcccccc',
            'aaabbbb',
            'abababab',
            'ababbbbc',
            'abcccccc',
            'babababa',
            'ababaaabc',
            'ababababa',
            'babababab',
            'aaaaaaaaac',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '[a-e]?',
        [
            '',
            'a',
            'b',
            'c',
            'd',
            'e',
        ]
    ], [
        'a\\d',
        [
            'a1',
        ]
    ], [
        '\\da',
        [
            '1a',
        ]
    ], [
        '\\d+',
        [
            '1',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '11',
            '111',
            '1111',
            '11111',
        ]
    ], [
        '\\d*',
        [
            '',
            '1',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '11',
            '111',
            '1111',
            '11111',
        ]
    ], [
        '\\d?',
        [
            '',
            '1',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
        ]
    ], [
        'a\\w',
        [
            'a1',
            'aa',
            'ab',
            'ac',
            'ad',
            'ae',
            'af',
            'ag',
            'ah',
        ]
    ], [
        '\\wa',
        [
            '1a',
            'aa',
            'ba',
        ]
    ], [
        '\\w+',
        [
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '1',
            '_',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
            '11',
            '1a',
            'a1',
            'aa',
            'ab',
            'ac',
            'ad',
            'ae',
            'af',
            'ag',
            'ah',
            'b1',
            'ba',
            'bb',
            'bc',
            'bd',
            'be',
            'bf',
            'bg',
            'cc',
            'cd',
            'ce',
            'cf',
            'gg',
            'aaa',
            'aab',
            'aac',
            'aad',
            'aba',
            'abb',
            'abc',
            'abd',
            'acc',
            'acd',
            'acg',
            'adf',
            'adg',
            'aeg',
            'afg',
            'baa',
            'bab',
            'bac',
            'bba',
            'bbb',
            'bbc',
            'bbd',
            'bca',
            'bcc',
            'bcd',
            'bcg',
            'bdf',
            'bdg',
            'beg',
            'bfg',
            'cba',
            'ccc',
            'ccd',
            'cdf',
            'cdg',
            'ceg',
            'cfg',
            'ggg',
            '111',
            'aaaa',
            'aaab',
            'aabd',
            'abab',
            'abac',
            'abbb',
            'abbc',
            'abcc',
            'abcd',
            'accc',
            'acdg',
            'addf',
            'adeg',
            'adfg',
            'aefg',
            'baba',
            'bbbb',
            'bbcd',
            'bccc',
            'bcdg',
            'bddf',
            'bdeg',
            'bdfg',
            'befg',
            'ccad',
            'cccc',
            'cddf',
            'cdeg',
            'cdfg',
            'cefg',
            'dcba',
            'gggg',
            '1111',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'ababc',
            'abbbb',
            'abccc',
            'acccc',
            'adddf',
            'adefg',
            'babab',
            'bbaac',
            'bbbbb',
            'bcccc',
            'bdddf',
            'bdefg',
            'ccccc',
            'cdddf',
            'cdefg',
            'ggggg',
            '11111',
            'abcde',
            'aabbb',
            'aaabb',
            'aaabac',
            'ababab',
            'abbbbb',
            'abcccc',
            'accccc',
            'acdcdg',
            'aefefg',
            'bababa',
            'bbbbbc',
            'bcdcdg',
            'befefg',
            'cccccc',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'abccccc',
            'adefefg',
            'bababab',
            'bcccccc',
            'bdefefg',
            'cdefefg',
            'aaabbbb',
            'abababab',
            'ababbbbc',
            'abcccccc',
            'babababa',
            'ababaaabc',
            'ababababa',
            'adefefefg',
            'babababab',
            'bdefefefg',
            'cdefefefg',
            'aaaaaaaaac',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '\\w*',
        [
            '',
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '1',
            '_',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
            '11',
            '1a',
            'a1',
            'aa',
            'ab',
            'ac',
            'ad',
            'ae',
            'af',
            'ag',
            'ah',
            'b1',
            'ba',
            'bb',
            'bc',
            'bd',
            'be',
            'bf',
            'bg',
            'cc',
            'cd',
            'ce',
            'cf',
            'gg',
            'aaa',
            'aab',
            'aac',
            'aad',
            'aba',
            'abb',
            'abc',
            'abd',
            'acc',
            'acd',
            'acg',
            'adf',
            'adg',
            'aeg',
            'afg',
            'baa',
            'bab',
            'bac',
            'bba',
            'bbb',
            'bbc',
            'bbd',
            'bca',
            'bcc',
            'bcd',
            'bcg',
            'bdf',
            'bdg',
            'beg',
            'bfg',
            'cba',
            'ccc',
            'ccd',
            'cdf',
            'cdg',
            'ceg',
            'cfg',
            'ggg',
            '111',
            'aaaa',
            'aaab',
            'aabd',
            'abab',
            'abac',
            'abbb',
            'abbc',
            'abcc',
            'abcd',
            'accc',
            'acdg',
            'addf',
            'adeg',
            'adfg',
            'aefg',
            'baba',
            'bbbb',
            'bbcd',
            'bccc',
            'bcdg',
            'bddf',
            'bdeg',
            'bdfg',
            'befg',
            'ccad',
            'cccc',
            'cddf',
            'cdeg',
            'cdfg',
            'cefg',
            'dcba',
            'gggg',
            '1111',
            'aabb',
            'aaba',
            'abaa',
            'baaa',
            'baab',
            'babb',
            'aaaaa',
            'ababa',
            'ababc',
            'abbbb',
            'abccc',
            'acccc',
            'adddf',
            'adefg',
            'babab',
            'bbaac',
            'bbbbb',
            'bcccc',
            'bdddf',
            'bdefg',
            'ccccc',
            'cdddf',
            'cdefg',
            'ggggg',
            '11111',
            'abcde',
            'aabbb',
            'aaabb',
            'aaabac',
            'ababab',
            'abbbbb',
            'abcccc',
            'accccc',
            'acdcdg',
            'aefefg',
            'bababa',
            'bbbbbc',
            'bcdcdg',
            'befefg',
            'cccccc',
            'aaaaaa',
            'aabbbb',
            'aaabbb',
            'abababa',
            'abccccc',
            'adefefg',
            'bababab',
            'bcccccc',
            'bdefefg',
            'cdefefg',
            'aaabbbb',
            'abababab',
            'ababbbbc',
            'abcccccc',
            'babababa',
            'ababaaabc',
            'ababababa',
            'adefefefg',
            'babababab',
            'bdefefefg',
            'cdefefefg',
            'aaaaaaaaac',
            'ababababab',
            'bababababa',
            'abababababa',
            'bababababab',
            'abababababab',
            'babababababa',
        ]
    ], [
        '\\w?',
        [
            '',
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            '1',
            '_',
            '0',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
        ]
    ], [
        '\\d\\w',
        [
            '11',
            '1a',
        ]
    ], [
        '()',
        [
            '',
        ]
    ], [
        '(())',
        [
            '',
        ]
    ], [
        '(a)',
        [
            'a',
        ]
    ], [
        '((a)b)',
        [
            'ab',
        ]
    ], [
        '(a(b))',
        [
            'ab',
        ]
    ], [
        '(a(b(c)))',
        [
            'abc',
        ]
    ], [
        '(((a)b)c)',
        [
            'abc',
        ]
    ], [
        '{',
        [
            '{',
        ]
    ], [
        '}',
        [
            '}',
        ]
    ], [
        '{{',
        [
            '{{',
        ]
    ], [
        '}}',
        [
            '}}',
        ]
    ], [
        '{}',
        [
            '{}',
        ]
    ], [
        '{{}}',
        [
            '{{}}',
        ]
    ], [
        '{a}',
        [
            '{a}',
        ]
    ], [
        '-',
        [
            '-',
        ]
    ], [
        '--',
        [
            '--',
        ]
    ], [
        '0-9',
        [
            '0-9',
        ]
    ], [
        'a-z',
        [
            'a-z',
        ]
    ], [
        '{-}',
        [
            '{-}',
        ]
    ], [
        '[a{1}]',
        False,
    ], [
        '|',
        False
    ], [
        'a|',
        False
    ], [
        '|a',
        False
    ], [
        '+',
        False
    ], [
        '+a',
        False
    ], [
        '?',
        False
    ], [
        '?a',
        False
    ], [
        'a**',
        False
    ], [
        'a++',
        False
    ], [
        'a??',
        False
    ], [
        'a*+',
        False
    ], [
        'a*?',
        False
    ], [
        'a*{0}',
        False
    ], [
        'a*{0,1}',
        False
    ], [
        'a{0}{0,1}',
        False
    ], [
        '(',
        False
    ], [
        ')',
        False
    ], [
        ')(',
        False
    ], [
        '())',
        False
    ], [
        '[',
        False
    ], [
        ']',
        False
    ], [
        '][',
        False
    ], [
        '[]]',
        False
    ], [
        '(]',
        False
    ], [
        '{2}',
        False
    ], [
        '{2}a',
        False
    ], [
        '{1,2}',
        False
    ], [
        '{1,2}a',
        False
    ], [
        '{2}{3}',
        False
    ], [
        '[a|b]',
        False
    ], [
        '[a*]',
        False
    ], [
        '[a+]',
        False
    ], [
        '[a?]',
        False
    ], [
        '[\\d]',
        False
    ], [
        '[\\w]',
        False
    ], [
        '[z-a]',
        False
    ], [
        ' ',
        [
            ' ',
        ]
    ], [
        '  ',
        [
            '  ',
        ]
    ], [
        'a ',
        [
            'a ',
        ]
    ], [
        ' '
        'a',
        [
            ' '
            'a',
        ]
    ], [
        'a '
        'b',
        [
            'a '
            'b',
        ]
    ], [
        ' '
        '|a',
        [
            'a',
            ' ',
        ]
    ], [
        'a| ',
        [
            'a',
            ' ',
        ]
    ], [
        ' '
        '+',
        [
            ' ',
            '  ',
            '   ',
        ]
    ], [
        ' '
        '*',
        [
            '',
            ' ',
            '  ',
            '   ',
        ]
    ], [
        ' '
        '?',
        [
            '',
            ' ',
        ]
    ]
]
